#ifndef ITEM_H
#define ITEM_H

#include "glm/glm.hpp"
#include <unordered_map>


enum class ItemID {NONE, GRASS_BLOCK, WATER_BLOCK, LAVA_BLOCK, STONE_BLOCK, COBBLESTONE_BLOCK, COAL_ORE, IRON_ORE, 
    GOLD_ORE, EMERALD_ORE, EMERALD_BLOCK, DIAMOND_BLOCK, GOLD_BLOCK, REDSTONE_BLOCK,
    IRON_BLOCK, STONE_BOCK, DIAMOND_ORE, REDSTONE_ORE, LAPIS_ORE, SNOW_GRASS_BLOCK, DIRT_BLOCK, 
    OAKPLANK_BLOCK, SPRUCEPLANK_BLOCK, BIRCHPLANK_BLOCK, BEDROCK_BLOCK, OAKLOG_BLOCK, OAKLEAVES_BLOCK,
    SAND_BLOCK, OBSIDIAN_BLOCK, GLOWSTONE_BLOCK, SPRUCELOG_BLOCK, SPRUCELEAVES_BLOCK, GLASS_BLOCK,
    BRICK_BLOCK,  STONEBRICK_BLOCK, SANDSTONE_BLOCK, BIRCHLOG_BLOCK, BIRCHLEAVES_BLOCK, CACTUS_BLOCK,
    GRAVEL_BLOCK, CRAFTINGTABLE_BLOCK, FURNACE_BLOCK, BARREL_BLOCK, ENCHANTMENT_TABLE_BLOCK, ANVIL, FISHING_ROD, ARROW, 

    BLACK_WOOL, BLUE_WOOL, BROWN_WOOL, CYAN_WOOL, GRAY_WOOL, GREEN_WOOL, LIGHTBLUE_WOOL, LIGHTGRAY_WOOL, MAGENTA_WOOL, 
    ORANGE_WOOL, LIME_WOOL, PINK_WOOL, PURPLE_WOOL, RED_WOOL, WHITE_WOOL, YELLOW_WOOL, 
    
    TNT_BLOCK, MELON_BLOCK, PUMPKIN_BLOCK, CLAY_BLOCK,
    OAK_SAPLING, BIRCH_SAPLING, DARKOAK_SAPLING, JUNGLE_SAPLING, SPRUCE_SAPLING, WHEAT, CARROT, MELON_SLICE,
    POTATO, COOKED_PORKCHOP, COOKED_BEEF, COOKED_CHICKEN, EGG, SEEDS, PUMPKIN_SEEDS, MELON_SEEDS, BEETROOT_SEEDS,
    COCOA_SEEDS, RAW_PORKCHOP, RAW_BEEF, RAW_CHICKEN, LEATHER, MILK_BUCKET, APPLE, BREAD, PUMPKINPIE, GOLDEN_APPLE,
    STRING, GUNPOWDER, SLIME_BALL, BLAZE_ROD, BONE, FIRE_CHARGE, SNOW_BALL, BRICK, FLINT, LAVA_BUCKET,
    WATER_BUCKET, BONEMEAL, BLAZE_POWDER, MORNINGSTAR, STAR_ARROW, BOW, NETHER_STAR, GLOWSTONE, CLAY_BALL, SUGAR,
    STICK, SHEARS, FEATHER, SUGAR_CANE,
    
    DIAMOND_HOE, DIAMOND_SHOVEL, DIAMOND_AXE, DIAMOND_PICKAXE, DIAMOND_SWORD, 
    HALLOWED_HOE, HALLOWED_SHOVEL, HALLOWED_AXE, HALLOWED_PICKAXE, HALLOWED_SWORD, GOLDEN_HOE, GOLDEN_SHOVEL,
    GOLDEN_AXE, GOLDEN_PICKAXE, GOLDEN_SWORD, STONE_SHOVEL, STONE_AXE, STONE_PICKAXE, STONE_SWORD,
    WOODEN_HOE, WOODEN_SHOVEL, WOODEN_AXE, WOODEN_PICKAXE, WOODEN_SWORD, IRON_HOE, IRON_SPADE, IRON_AXE,
    IRON_PICKAXE, IRON_SWORD, STONE_HOE, IRON_SHOVEL,
    
    DIAMOND_HELMET, DIAMOND_BREASTPLATE, DIAMOND_LEGGINGS, DIAMOND_BOOTS, HALLOWED_HELMET,
    HALLOWED_BREASTPLATE, HALLOWED_LEGGINGS, HALLOWED_BOOTS, GOLDEN_HELMET, GOLDEN_BREASTPLATE, GOLDEN_LEGGINGS, GOLDEN_BOOTS, IRON_HELMET,
    IRON_BREASTPLATE, IRON_LEGGINGS, IRON_BOOTS, LEATHER_HELMET, LEATHER_BREASTPLATE, LEATHER_LEGGINGS, LEATHER_BOOTS,
    DIAMOND_HORSE_ARMOR,
    
    GOLD_HORSE_ARMOR, IRON_HORSE_ARMOR, LEATHER_HORSE_ARMOR,
    
    DIAMOND, HALLOWED_BAR, GOLD_BAR,
    IRON_BAR, REDSTONE, LAPIS, COAL, EMERALD,
    
    BROWN_DYE, BLUE_DYE, CYAN_DYE, LIGHTGRAY_DYE, GREEN_DYE, WHITE_DYE, LIGHTBLUE_DYE,
    LIME_DYE, PINK_DYE, ORANGE_DYE, RED_DYE, MAGENTA_DYE, PURPLE_DYE, YELLOW_DYE, 
    
    TORCH, 
    
    ROSE, YELLOW_FLOWER
};

enum class ToolType {
    NONE,
    SWORD, PICKAXE, AXE, SHOVEL, HOE,
    ARMOR
};

enum class ItemType {
    NONE, 
    ITEM, BLOCK
};

enum class BlockType {
    STONE = 0,
    WOOD = 1,
    DIRT = 2,
    LEAVES = 3,
    SAND = 4,
    GLASS = 5,
    WOOL = 6,
    ORE = 7,
    PLANT = 8,
    OTHER = 9
};

struct ItemData {
    ItemType itemType = ItemType::ITEM;
    ToolType toolType = ToolType::NONE;

    int maxStackSize = 64;
    double speed = 1.0;
    double damage = 1.0;
    int durability = 0;

    bool placeable = false;
};

class Item {
    public:
        Item(ItemID newID, int newQuantity = 1);

        static glm::vec2* getUVCoords(ItemID itemIeED);
        static void setAtlasUVCoords(glm::vec2* uvs, int xPos, int yPos);

        ItemData itemData;

        ItemID id;

        int maxQuantity;
        int quantity;

        ItemID getID();
        ItemType getItemType();

        int getQuantity();
        int getMaxQuantity();

        void setQuantity(int amount);

        int addQuantity(int amount);

        bool subtractOne();
        bool subtractQuantity(int amount);
        bool putOnSlot(Item* slotItem);
        bool isPlaceable();
        bool subtractDurability();

        float getMultiplier(ItemID blockType, ItemID heldItem);
        
    protected:

};

#endif